import React from "react";
import "./App.css";
import NavBar from "./components/navBar/NavBar";
import CustomCarousel from "./components/carousel/Carousel";
import HomeMessage from "./components/home-message/HomeMessage";
import { Parallax } from "react-parallax";
import Slide from "react-reveal/Slide";
import Container from "react-bootstrap/Container";
import About from "./views/about/About";
import Skills from "./views/skills/Skills";
import Portfolio from "./views/portfolio/Portfolio";
import Contact from "./views/contact/Contact";
import Resume from "./views/resume/Resume";
import Footer from "./components/footer/Footer";